version: '3.8'

services:
  pac-nginx:
    build:
      context: .
      dockerfile: pac-nginx.Dockerfile
    container_name: pac-nginx
    image: nginx:alpine
    ports:
      - 127.0.0.1:80:80/tcp
    restart: unless-stopped
    tty: true
    volumes:
        - type: bind
          source: ./pac.conf
          target: /etc/nginx/nginx.conf
        - type: bind
          source: ./proxy.pac
          target: /srv/pac/proxy.pac
